### ISSUE TITLE
Board creation and permissions to access each other's board

### ISSUE THREAD

**Issue by Ciaranengelbrecht** [DJRyLau/CITS3403-Project#35]
Implemented functionality of board creations and adding other users to access the board, then switching boards with unique note elements on each, being able to see and edit eachother's notes on the same board and renaming of the board page based on title.
<img width="1436" alt="Screenshot 2024-05-18 at 4 27 54 PM" src="https://github.com/DJRyLau/CITS3403-Project/assets/131735166/eb243d9e-77fa-4124-8368-d8b0f8968e92">
<img width="1428" alt="Screenshot 2024-05-18 at 4 27 36 PM" src="https://github.com/DJRyLau/CITS3403-Project/assets/131735166/074e0236-ff6e-438a-8c23-d05e30adbfe2">

**Comment by darkksuns** [comment]
LOL the "please be working" is so real.
This is really good! Looks really clean and it works really well on my end too 👍
